spring.application.name=teamtaskmanager

spring.datasource.url=jdbc:postgresql://localhost:5432/teamtaskmanager
spring.datasource.username=postgres
spring.datasource.password=Shruti1908
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080